// packages/fiveway-react/src/item.ts
import { type ReactNode, useRef, useEffect } from "react";
import {
  type NodeId,
  type ItemNode,
  createItemNode,
  updateNode,
  connectNode,
  removeNode,
} from "@fiveway/core";
import { useNavigationContext } from "./context.js";
import type { NodeHandle, NodeOptions } from "./node.js";
import {
  useFocus,
  useSelect,
  useRegisterElement,
  useLazyIsFocused,
} from "./hooks.js";

export type ItemHandle = NodeHandle & {
  select: (nodeId?: NodeId, focus?: boolean) => void;
};

export type ItemOptions = NodeOptions & {
  onSelect?: () => void;
};

export function useNavigationItem(options: ItemOptions): ItemHandle {
  const { tree, parentNode } = useNavigationContext();
  const parentId = options.parent ?? parentNode;

  const nodeRef = useRef<ItemNode>(null as unknown as ItemNode);
  if (nodeRef.current === null) {
    nodeRef.current = createItemNode(tree, {
      id: options.id,
      parent: parentId,
      handler: options.handler,
      focusable: options.focusable,
      onSelect: options.onSelect,
      order: options.order,
    });
  } else {
    updateNode(nodeRef.current, options);
  }
  const nodeId = nodeRef.current.id;

  useEffect(() => {
    connectNode(tree, nodeRef.current);

    return () => {
      removeNode(tree, nodeId);
    };
  }, [tree, nodeId]);

  const registerElement = useRegisterElement(nodeRef.current);

  const isFocused = useLazyIsFocused(tree, nodeId);
  const focus = useFocus(nodeId);
  const select = useSelect(nodeId);

  return {
    id: nodeId,
    isFocused,
    focus: (id, options) => focus(id ?? nodeId, options),
    select: (id, focus) => select(id ?? nodeId, focus),
    provide: (provider, value) => provider.provide(nodeRef.current, value),
    registerElement,
  };
}

type ItemProps = ItemOptions & {
  children: ReactNode | ((handle: ItemHandle) => ReactNode);
};

export function NavigationItem({ children, ...props }: ItemProps) {
  const node = useNavigationItem(props);

  return typeof children === "function" ? children(node) : children;
}

// packages/fiveway-solid/src/item.ts
import {
  type JSX,
  createEffect,
  onCleanup,
  on,
  splitProps,
  children,
} from "solid-js";
import { createLazyMemo } from "@solid-primitives/memo";
import {
  type NodeId,
  type FocusOptions,
  createItemNode,
  connectNode,
  updateNode,
  removeNode,
  PositionProvider,
  isFocused,
  focusNode,
  scopedId,
  selectNode,
} from "@fiveway/core";
import { useNavigationContext } from "./context.js";
import { ElementProvider } from "./hooks.jsx";
import type { NodeHandle, NodeOptions } from "./node.jsx";

export type ItemOptions = NodeOptions & {
  onSelect?: () => void;
};

export type ItemHandle = NodeHandle & {
  select: () => void;
};

export function createNavigationItem(options: ItemOptions): ItemHandle {
  const { tree, parentNode, focusedId } = useNavigationContext();

  const node = createItemNode(tree, {
    id: options.id,
    parent: options.parent ?? parentNode,
    order: options.order,
    onSelect: options.onSelect,
    focusable: options.focusable,
    handler: options.handler,
  });

  createEffect(() => {
    connectNode(tree, node);

    createEffect(() => {
      updateNode(node, options);
    });

    onCleanup(() => {
      removeNode(tree, node.id);
    });
  });

  const registerElement = (el: HTMLElement) => {
    ElementProvider.provide(node, el);

    PositionProvider.provide(node, () => {
      return el.getBoundingClientRect();
    });
  };

  return {
    id: node.id,
    isFocused: createLazyMemo(on(focusedId, () => isFocused(tree, node.id))),
    focus: (nodeId?: NodeId, options?: FocusOptions) => {
      return focusNode(
        tree,
        nodeId != null ? scopedId(parentNode, nodeId) : node.id,
        options
      );
    },
    select: (nodeId?: NodeId) => {
      selectNode(tree, nodeId != null ? scopedId(parentNode, nodeId) : node.id);
    },
    registerElement,
    provide: (provider, value) => {
      provider.provide(node, value);
    },
  };
}

export type ItemProps = ItemOptions & {
  children: JSX.Element | ((node: ItemHandle) => JSX.Element);
};

export function NavigationItem(props: ItemProps) {
  const [, options] = splitProps(props, ["children"]);
  const node = createNavigationItem(options);

  return children(() => {
    const child = props.children;

    return typeof child === "function" ? child(node) : child;
  })();
}
