// packages/fiveway-react/src/NavigationProvider.tsx
import { type PropsWithChildren, useEffect, useRef } from "react";
import {
  type NavigationAction,
  type NavigationTree,
  handleAction,
  registerFocusListener,
  getNode,
} from "@fiveway/core";
import { defaultEventMapping } from "@fiveway/core/dom";
import { NavigationContext } from "./context.js";
import { ElementProvider } from "./hooks.js";

export type NavigationProviderProps = PropsWithChildren<{
  tree: NavigationTree;
  fromEvent?: (e: KeyboardEvent) => NavigationAction | null;
}>;

export function NavigationProvider({
  tree,
  children,
  fromEvent = defaultEventMapping,
}: NavigationProviderProps) {
  const handlerRef = useRef((e: KeyboardEvent) => {
    const action = fromEvent(e);
    if (action === null) {
      return;
    }

    handleAction(tree, action);
  });

  useEffect(() => {
    const handler = handlerRef.current;
    window.addEventListener("keydown", handler);

    return () => {
      window.removeEventListener("keydown", handler);
    };
  }, []);

  useEffect(() => {
    const handler = () => {
      const node = getNode(tree, tree.focusedId);
      const el = ElementProvider.extract(node);
      if (el != null) {
        el.focus();
      }
    };

    return registerFocusListener(tree, {
      type: "focuschange",
      node: "#",
      fn: handler,
    });
  }, [tree]);

  return (
    <NavigationContext.Provider value={{ tree, parentNode: tree.root.id }}>
      {children}
    </NavigationContext.Provider>
  );
}

// packages/fiveway-solid/src/NavigationProvider.tsx
import { type JSX, createSignal, onCleanup, createEffect } from "solid-js";
import {
  type NavigationAction,
  type NavigationTree,
  handleAction,
  registerFocusListener,
  getNode,
} from "@fiveway/core";
import { defaultEventMapping } from "@fiveway/core/dom";
import { NavigationContext } from "./context.js";
import { ElementProvider } from "./hooks.jsx";

type NavigationProviderProps = {
  tree: NavigationTree;
  fromEvent?: (e: KeyboardEvent) => NavigationAction | null;
  children: JSX.Element;
};

export function NavigationProvider(props: NavigationProviderProps) {
  // reactive tree prop is not supported
  // eslint-disable-next-line solid/reactivity
  const tree = props.tree;

  const [focusedId, setFocusedId] = createSignal(tree.focusedId);

  const cleanupFocusListener = registerFocusListener(tree, {
    type: "focuschange",
    node: "#",
    fn: () => {
      setFocusedId(tree.focusedId);
    },
  });

  const handler = (e: KeyboardEvent) => {
    const mapFn = props.fromEvent ?? defaultEventMapping;

    const action = mapFn(e);
    if (action === null) {
      return;
    }

    handleAction(tree, action);
  };
  window.addEventListener("keydown", handler);

  onCleanup(() => {
    cleanupFocusListener();
    window.removeEventListener("keydown", handler);
  });

  createEffect(() => {
    const node = getNode(tree, focusedId());
    const el = ElementProvider.extract(node);
    if (el !== null) {
      el.focus();
    } else if (document.activeElement instanceof HTMLElement) {
      document.activeElement.blur();
    }
  });

  return (
    <NavigationContext.Provider
      value={{ tree, parentNode: tree.root.id, focusedId }}
    >
      {props.children}
    </NavigationContext.Provider>
  );
}
