// packages/fiveway-solid/src/container.tsx
import {
  type Component,
  type ParentProps,
  createEffect,
  onCleanup,
  on,
  splitProps,
  children,
  type JSX,
} from "solid-js";
import { createLazyMemo } from "@solid-primitives/memo";
import {
  type NodeId,
  createContainerNode,
  connectNode,
  updateNode,
  removeNode,
  PositionProvider,
  isFocused,
  focusNode,
  scopedId,
  type FocusOptions,
} from "@fiveway/core";
import { ElementProvider } from "./hooks.jsx";
import { useNavigationContext } from "./context.js";
import { NodeContext, type NodeHandle, type NodeOptions } from "./node.jsx";

export type ContainerOptions = NodeOptions & {
  initial?: NodeId;
  captureFocus?: boolean;
};

export type ContainerHandle = NodeHandle & {
  Context: Component<ParentProps>;
};

export function createNavigationContainer(
  options: ContainerOptions
): ContainerHandle {
  const { tree, parentNode, focusedId } = useNavigationContext();

  const node = createContainerNode(tree, {
    id: options.id,
    parent: options.parent ?? parentNode,
    initial: options.initial,
    order: options.order,
    captureFocus: options.captureFocus,
    focusable: options.focusable,
    handler: options.handler,
  });

  createEffect(() => {
    connectNode(tree, node);

    createEffect(() => {
      updateNode(node, options);
    });

    onCleanup(() => {
      removeNode(tree, node.id);
    });
  });

  const registerElement = (el: HTMLElement) => {
    ElementProvider.provide(node, el);

    PositionProvider.provide(node, () => {
      return el.getBoundingClientRect();
    });
  };

  return {
    id: node.id,
    isFocused: createLazyMemo(on(focusedId, () => isFocused(tree, node.id))),
    focus: (nodeId?: NodeId, options?: FocusOptions) => {
      return focusNode(
        tree,
        nodeId != null ? scopedId(parentNode, nodeId) : node.id,
        options
      );
    },
    provide: (provider, value) => {
      createEffect(() => {
        provider.provide(node, value());
      });
    },
    registerElement,
    Context: (props: ParentProps) => (
      <NodeContext node={node.id}>{props.children}</NodeContext>
    ),
  };
}

export type ContainerProps = ContainerOptions & {
  children?:
    | ((node: Omit<ContainerHandle, "Context">) => JSX.Element)
    | JSX.Element;
};

export function NavigationContainer(props: ContainerProps) {
  const [, options] = splitProps(props, ["children"]);
  const { Context, ...node } = createNavigationContainer(options);

  return (
    <Context>
      {children(() => {
        const child = props.children;

        return typeof child === "function" ? child(node) : child;
      })()}
    </Context>
  );
}

// packages/fiveway-react/src/container.tsx
import { type ReactNode, useRef, useEffect, useCallback } from "react";
import {
  type NodeId,
  type ContainerNode,
  createContainerNode,
  updateNode,
  connectNode,
  removeNode,
} from "@fiveway/core";
import { useNavigationContext, NavigationContext } from "./context.js";
import type { NodeOptions, NodeHandle } from "./node.js";
import { useFocus, useLazyIsFocused, useRegisterElement } from "./hooks.js";

export type ContainerOptions = NodeOptions & {
  initial?: NodeId;
  captureFocus?: boolean;
};

export type ContainerHandle = NodeHandle & {
  Context: React.FunctionComponent<{ children: ReactNode }>;
};

export function useNavigationContainer(
  options: ContainerOptions
): ContainerHandle {
  const { tree, parentNode } = useNavigationContext();
  const parent = options.parent ?? parentNode;

  const nodeRef = useRef<ContainerNode>(null as unknown as ContainerNode);
  if (nodeRef.current === null) {
    nodeRef.current = createContainerNode(tree, {
      id: options.id,
      parent,
      initial: options.initial,
      handler: options.handler,
      focusable: options.focusable,
      captureFocus: options.captureFocus,
      order: options.order,
    });
  } else {
    updateNode(nodeRef.current, options);
  }
  const nodeId = nodeRef.current.id;

  useEffect(() => {
    connectNode(tree, nodeRef.current);

    return () => {
      removeNode(tree, nodeId);
    };
  }, [tree, nodeId]);

  const registerElement = useRegisterElement(nodeRef.current);

  const Context: ContainerHandle["Context"] = useCallback(
    (props: { children: ReactNode }) => {
      const context = {
        tree: tree,
        parentNode: nodeId,
      };

      return (
        <NavigationContext.Provider value={context}>
          {props.children}
        </NavigationContext.Provider>
      );
    },
    [tree, nodeId]
  );

  Context.displayName = "NavigationContext";

  const isFocused = useLazyIsFocused(tree, nodeId);
  const focus = useFocus(nodeId);

  return {
    id: nodeId,
    isFocused,
    focus: (id, options) => focus(id ?? nodeId, options),
    provide: (provider, value) => provider.provide(nodeRef.current, value),
    Context,
    registerElement,
  };
}

type ContainerProps = ContainerOptions & {
  children?:
    | ReactNode
    | ((props: Omit<ContainerHandle, "Context">) => ReactNode);
};

export function NavigationContainer({ children, ...props }: ContainerProps) {
  const { Context, ...node } = useNavigationContainer(props);

  return (
    <Context>
      {typeof children === "function" ? children(node) : children}
    </Context>
  );
}
