// packages/fiveway-solid/src/context.ts
import { createContext, useContext, type Accessor } from "solid-js";
import { type NavigationTree, type NodeId } from "@fiveway/core";

export type NavigationContext = {
  tree: NavigationTree;
  parentNode: NodeId;
  focusedId: Accessor<NodeId>;
};

export const NavigationContext = createContext<NavigationContext | null>(null);

export function useNavigationContext(): NavigationContext {
  const navContext = useContext(NavigationContext);
  if (navContext == null) {
    throw new Error("expected navigation context");
  }

  return navContext;
}

// packages/fiveway-react/src/context.tsx
import { createContext, useContext, type PropsWithChildren } from "react";
import { type NavigationTree, type NodeId } from "@fiveway/core";

export type NavigationContext = {
  tree: NavigationTree;
  parentNode: NodeId;
};

export const NavigationContext = createContext<NavigationContext | null>(null);

export type NavigationProviderProps = PropsWithChildren<{
  tree: NavigationTree;
}>;

export function NavigationProvider(props: NavigationProviderProps) {
  return (
    <NavigationContext.Provider value={{ tree: props.tree, parentNode: "#" }}>
      {props.children}
    </NavigationContext.Provider>
  );
}

export function useNavigationContext(): NavigationContext {
  const navContext = useContext(NavigationContext);
  if (navContext == null) {
    throw new Error("expected navigation context");
  }

  return navContext;
}
