// packages/fiveway-solid/src/hooks.ts
import {
  type Accessor,
  createEffect,
  createMemo,
  createSignal,
  onCleanup,
} from "solid-js";
import {
  type NodeId,
  type FocusOptions,
  selectNode,
  scopedId,
  focusNode,
  isFocused,
  registerListener,
} from "@fiveway/core";
import { useNavigationContext } from "./context.jsx";

export function useIsFocused(
  nodeId: NodeId | Accessor<NodeId>,
): Accessor<boolean> {
  const { tree, parentNode } = useNavigationContext();
  const globalId = createMemo(() => {
    const id = typeof nodeId === "function" ? nodeId() : nodeId;
    return scopedId(parentNode(), id);
  });

  const [isNodeFocused, setFocused] = createSignal<boolean | null>(null);

  let subscription: (() => void) | null = null;
  const subscribe = (id: NodeId) =>
    registerListener(tree, id, "focuschange", () => {
      setFocused(isFocused(tree, id));
    });

  createEffect(() => {
    const id = globalId();

    if (subscription !== null) {
      subscription();
      subscription = subscribe(id);
    }
  });

  onCleanup(() => {
    subscription?.();
  });

  const getter = () => {
    const id = globalId();

    if (subscription === null) {
      subscription = subscribe(id);
    }

    return isNodeFocused() ?? isFocused(tree, id);
  };

  return getter;
}

export function useOnFocus(
  nodeId: NodeId,
  handler: (id: NodeId | null) => void,
) {
  const { tree, parentNode } = useNavigationContext();
  const globalId = scopedId(parentNode(), nodeId);

  createEffect(() => {
    const cleanup = registerListener(tree, globalId, "focuschange", () => {
      const id = isFocused(tree, globalId) ? tree.focusedId : null;
      handler(id);
    });

    onCleanup(cleanup);
  });
}

export function useFocusedId(scope: NodeId) {
  const { tree, parentNode } = useNavigationContext();
  const globalId = scopedId(parentNode(), scope);
  const [focusedId, setFocusedId] = createSignal(
    isFocused(tree, globalId) ? tree.focusedId : null,
  );

  createEffect(() => {
    const cleanup = registerListener(tree, globalId, "focuschange", () => {
      const id = isFocused(tree, globalId) ? tree.focusedId : null;
      setFocusedId(id);
    });

    onCleanup(cleanup);
  });

  return focusedId;
}

export function useFocus(scope?: NodeId) {
  const { tree, parentNode } = useNavigationContext();
  scope ??= parentNode();

  return (nodeId: NodeId, options?: FocusOptions) => {
    return focusNode(tree, scopedId(scope, nodeId), options);
  };
}

export function useSelect(scope?: NodeId) {
  const { tree, parentNode } = useNavigationContext();
  scope ??= parentNode();

  return (nodeId: NodeId, focus?: boolean) => {
    selectNode(tree, scopedId(scope, nodeId), focus);
  };
}

// packages/fiveway-react/src/hooks.ts
import { useCallback, useEffect, useSyncExternalStore, useRef } from "react";
import {
  type NodeId,
  type FocusOptions,
  selectNode,
  isFocused,
  registerListener,
  focusNode,
  scopedId,
} from "@fiveway/core";
import { useNavigationContext } from "./context.js";

export function useIsFocused(nodeId: NodeId) {
  const { tree, parentNode } = useNavigationContext();
  const globalId = scopedId(parentNode, nodeId);

  const subscribe = useCallback(
    (cb: () => void) => registerListener(tree, globalId, "focuschange", cb),
    [tree, globalId]
  );

  return useSyncExternalStore(subscribe, () => isFocused(tree, globalId));
}

export function useOnFocus(
  nodeId: NodeId,
  handler: (id: NodeId | null) => void
) {
  const { tree, parentNode } = useNavigationContext();
  const globalId = scopedId(parentNode, nodeId);

  const handlerRef = useRef(handler);
  handlerRef.current = handler;

  useEffect(() => {
    return registerListener(tree, globalId, "focuschange", (e) => {
      const id = isFocused(tree, globalId) ? e.focused : null;
      handlerRef.current(id);
    });
  }, [globalId]);
}

export function useFocusedId(scope: NodeId) {
  const { tree, parentNode } = useNavigationContext();
  const globalId = scopedId(parentNode, scope);

  const subscribe = useCallback(
    (cb: () => void) => registerListener(tree, globalId, "focuschange", cb),
    [tree, globalId]
  );

  return useSyncExternalStore(subscribe, () =>
    isFocused(tree, globalId) ? tree.focusedId : null
  );
}

export function useFocus(
  scope?: NodeId
): (nodeId: NodeId, options?: FocusOptions) => boolean {
  const { tree, parentNode } = useNavigationContext();
  scope ??= parentNode;

  return useCallback(
    (nodeId: NodeId, options?: FocusOptions) => {
      return focusNode(tree, scopedId(scope, nodeId), options);
    },
    [tree, scope]
  );
}

export function useSelect(scope?: NodeId) {
  const { tree, parentNode } = useNavigationContext();
  scope ??= parentNode;

  return useCallback(
    (nodeId: NodeId, focus?: boolean) => {
      selectNode(tree, scopedId(scope, nodeId), focus);
    },
    [tree, scope]
  );
}
